sonar.projectKey=wallet-app-ios
sonar.projectName=wallet-app-ios

sonar.sources=.
sonar.exclusions=**/Pods/**,**/.build/**,**/DerivedData/**,**/*.generated.swift

sonar.coverageReportPaths=sonar-coverage.xml