name: Setup Env
description: Sets up Xcode version and upgrades bash

inputs:
  xcode-version:
    required: true

runs:
  using: composite
  steps:
    - run: sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode-version }}.app
      shell: bash

    - run: brew install bash
      shell: bash
