# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: Xcode Build
description: Restore Xcode cache, generate project, and build for testing to warm the cache

inputs:
  should-restore-xcode-cache:
  description: "Conditional for restoring xcode cache"
  required: false
  default: "false"

runs:
  using: composite
  steps:
    - name: Restore Xcode cache
      uses: ./.github/actions/xcode-cache-restore

    - name: Generate Xcode project
      shell: bash
      run: xcodegen generate --use-cache --cache-path .xcodegen/cache

    - name: Build
      shell: bash
      run: |
        set -o pipefail
        xcodebuild build-for-testing \
          -workspace Wallet.xcworkspace \
          -scheme WalletTests \
          -destination 'platform=iOS Simulator,name=iPhone 17' \
          COMPILER_INDEX_STORE_ENABLE=NO \
        | xcbeautify
