name: Pull request

on:
  pull_request:

permissions:
  contents: read

jobs:
  commit-lint:
    uses: diggsweden/.github/.github/workflows/commit-lint.yml@main

  dependency-review-lint:
    uses: diggsweden/.github/.github/workflows/dependency-review.yml@main

  licenselint:
    uses: diggsweden/.github/.github/workflows/license-lint.yml@main

  misclint:
    permissions:
      contents: read
      security-events: write
    uses: diggsweden/.github/.github/workflows/megalint.yml@main

  lint:
    runs-on: ${{ vars.MACOS_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
        with:
          xcode-version: ${{ vars.XCODE_VERSION }}

      - name: Install swift-format
        run: brew install swift-format

      - name: 🧹 Run linter
        run: |
          printf "\n==> Linting...\n"
          ./scripts/lint.sh

  unit-tests:
    runs-on: ${{ vars.MACOS_VERSION }}
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
        with:
          xcode-version: ${{ vars.XCODE_VERSION }}

      - name: 🧪 Run unit tests
        run: |
          set -o pipefail
          xcodebuild test \
            -scheme WalletTests \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
          | xcbeautify

  # TODO: Uncomment when we have implemented UI tests
  # ui-tests:
  #   runs-on: ${{ vars.MACOS_VERSION }}
  #   needs: lint
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setup-env
  #       with:
  #         xcode-version: ${{ vars.XCODE_VERSION }}
  #
  #     - name: 📱 Run UI tests
  #       run: |
  #         set -o pipefail
  #         xcodebuild test \
  #           -scheme WalletUITests \
  #           -destination 'platform=iOS Simulator,name=iPhone 16' \
  #         | xcbeautify
